name: bluebuild
on:
  schedule:
    - cron: "00 17 * * *"
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        recipe:
          - recipe.yml
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create Dummy Cosign File
        run: |
          # The tool crashes if this file is missing, even if we don't use it.
          # We create a fake one to bypass the check.
          touch cosign.pub

      - name: Build Image
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # 1. We force the directory to be "safe" for Git
          # 2. We run the build with --verbose (-v) to see errors if they happen
          docker run --rm \
            --privileged \
            -v ${{ github.workspace }}:/github/workspace \
            -w /github/workspace \
            -e GITHUB_TOKEN=${{ github.token }} \
            -e COSIGN_PRIVATE_KEY="" \
            --entrypoint /bin/sh \
            ghcr.io/blue-build/cli:latest \
            -c "git config --global --add safe.directory /github/workspace && \
                bluebuild build ./recipes/${{ matrix.recipe }} \
                --registry ghcr.io \
                --registry-namespace $(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]') \
                --push \
                --no-sign \
                -v"
